In [1]:
!pip install datawrapper

Collecting datawrapper
  Downloading datawrapper-2.0.11-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: importlib_metadata in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from datawrapper) (8.4.0)
Collecting rich (from datawrapper)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: requests in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from datawrapper) (2.32.3)
Requirement already satisfied: pandas in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from datawrapper) (2.2.2)
Collecting pydantic (from datawrapper)
  Downloading pydantic-2.12.4-py3-none-any.whl.metadata (89 kB)
Requirement already satisfied: ipython in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from datawrapper) (8.26.0)
Requirement already satisfied: zipp>=0.5 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from importlib_metadata->datawrapper) (3.20.1)
Requirement already satisfied: decorator in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (3.0.47)
Requirement already satisfied: pygments>=2.4.0 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (2.18.0)
Requirement already satisfied: stack-data in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (0.6.2)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (5.14.3)
Requirement already satisfied: colorama in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from ipython->datawrapper) (0.4.6)
Requirement already satisfied: numpy>=1.26.0 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from pandas->datawrapper) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from pandas->datawrapper) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from pandas->datawrapper) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from pandas->datawrapper) (2024.1)
Collecting annotated-types>=0.6.0 (from pydantic->datawrapper)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic->datawrapper)
  Downloading pydantic_core-2.41.5-cp312-cp312-win_amd64.whl.metadata (7.4 kB)
Collecting typing-extensions>=4.14.1 (from pydantic->datawrapper)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic->datawrapper)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from requests->datawrapper) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from requests->datawrapper) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from requests->datawrapper) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from requests->datawrapper) (2024.7.4)
Collecting markdown-it-py>=2.2.0 (from rich->datawrapper)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from jedi>=0.16->ipython->datawrapper) (0.8.4)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->datawrapper)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: wcwidth in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->datawrapper) (0.2.13)
Requirement already satisfied: six>=1.5 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from python-dateutil>=2.8.2->pandas->datawrapper) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from stack-data->ipython->datawrapper) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from stack-data->ipython->datawrapper) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\carol\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (from stack-data->ipython->datawrapper) (0.2.3)
Downloading datawrapper-2.0.11-py3-none-any.whl (101 kB)
Downloading pydantic-2.12.4-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp312-cp312-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 18.7 MB/s eta 0:00:00
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: typing-extensions, mdurl, annotated-types, typing-inspection, pydantic-core, markdown-it-py, rich, pydantic, datawrapper
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
Successfully installed annotated-types-0.7.0 datawrapper-2.0.11 markdown-it-py-4.0.0 mdurl-0.1.2 pydantic-2.12.4 pydantic-core-2.41.5 rich-14.2.0 typing-extensions-4.15.0 typing-inspection-0.4.2

In [2]:
%env DATAWRAPPER_ACCESS_TOKEN=

env:

In [3]:
import datawrapper as dw

In [4]:
dw.Datawrapper () .get_my_account()

{'id': 1012121,
 'email': 'carolinejones942@gmail.com',
 'name': 'Caroline Jones',
 'role': 'editor',
 'language': 'en-US',
 'presenceColor': 'color-dw-presence-70',
 'avatar': 'https://lh3.googleusercontent.com/a/ACg8ocK6GcyhmRAH9Bsg8vOMUNGnROpvEwoiOONjK42q97XPJFbldp4Sqw=s96-c',
 'customAvatar': 'https://lh3.googleusercontent.com/a/ACg8ocK6GcyhmRAH9Bsg8vOMUNGnROpvEwoiOONjK42q97XPJFbldp4Sqw=s96-c',
 'teams': [],
 'workspaces': [{'slug': 'yimgiybidm',
   'name': 'Caroline Jones',
   'avatar': 'https://lh3.googleusercontent.com/a/ACg8ocK6GcyhmRAH9Bsg8vOMUNGnROpvEwoiOONjK42q97XPJFbldp4Sqw=s96-c',
   'color': 'color-dw-presence-70',
   'personalAppearance': True}],
 'chartCount': 6,
 'url': '/v3/users/1012121',
 'activeTeam': None}

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/palewire/first-automated-chart/main/_notebooks/arrests.csv",
    parse_dates=["ArrestDateTime"])

In [7]:
df

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368514,369385,1.408062e+06,605113.277780,10A00005,10000039.0,17.0,M,B,2010-01-01 00:05:00,2900 NORFOLK AV,...,HAND GUN VIOLATION,Northwest,612.0,Park Circle,39.3277,-76.6616,"(39.3277,-76.6616)",NaN,2010,2010
368515,369386,1.436274e+06,603484.911890,10A00011,10000077.0,20.0,M,B,2010-01-01 00:05:00,3500 SHANNON DR,...,CONTROLLED SUBSTANCE,Northeast,432.0,Lower Herring Run Park,39.3229,-76.5619,"(39.3229,-76.5619)",NaN,2010,2010
368516,369387,1.401876e+06,594236.816091,10A00009,10000013.0,28.0,M,B,2010-01-01 00:01:00,900 WILDWOOD PW,...,HANDGUN VIOLATION,Southwest,815.0,Edmondson Village,39.2979,-76.6836,"(39.2979,-76.6836)",NaN,2010,2010
368517,369388,1.428992e+06,599772.172473,10A00024,10000018.0,25.0,M,B,2010-01-01 00:01:00,1900 COLLINGTON AV,...,DISTRIBUTION HERION,Eastern,331.0,South Clifton Park,39.3128,-76.5877,"(39.3128,-76.5877)",NaN,2010,2010
368518,369389,1.416216e+06,596366.646274,10A00069,10000083.0,21.0,M,B,2010-01-01 00:00:00,1600 DIVISION ST,...,CONTROLLED SUBSTANCE,Central,123.0,Upton,39.3036,-76.6329,"(39.3036,-76.6329)",NaN,2010,2010

In [8]:
df.head ()

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022

In [9]:
df['year'] = df.ArrestDateTime.dt.year

In [10]:
df.year.value_counts()

year
2010    45224
2011    43364
2012    42333
2013    39542
2014    37078
2015    25732
2016    23089
2017    21989
2018    20543
2019    19407
2023    13566
2020    13162
2022    12360
2021    11130
Name: count, dtype: int64

In [11]:
totals_by_year = df.year.value_counts().sort_index().reset_index()

In [12]:
df

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368514,369385,1.408062e+06,605113.277780,10A00005,10000039.0,17.0,M,B,2010-01-01 00:05:00,2900 NORFOLK AV,...,HAND GUN VIOLATION,Northwest,612.0,Park Circle,39.3277,-76.6616,"(39.3277,-76.6616)",NaN,2010,2010
368515,369386,1.436274e+06,603484.911890,10A00011,10000077.0,20.0,M,B,2010-01-01 00:05:00,3500 SHANNON DR,...,CONTROLLED SUBSTANCE,Northeast,432.0,Lower Herring Run Park,39.3229,-76.5619,"(39.3229,-76.5619)",NaN,2010,2010
368516,369387,1.401876e+06,594236.816091,10A00009,10000013.0,28.0,M,B,2010-01-01 00:01:00,900 WILDWOOD PW,...,HANDGUN VIOLATION,Southwest,815.0,Edmondson Village,39.2979,-76.6836,"(39.2979,-76.6836)",NaN,2010,2010
368517,369388,1.428992e+06,599772.172473,10A00024,10000018.0,25.0,M,B,2010-01-01 00:01:00,1900 COLLINGTON AV,...,DISTRIBUTION HERION,Eastern,331.0,South Clifton Park,39.3128,-76.5877,"(39.3128,-76.5877)",NaN,2010,2010
368518,369389,1.416216e+06,596366.646274,10A00069,10000083.0,21.0,M,B,2010-01-01 00:00:00,1600 DIVISION ST,...,CONTROLLED SUBSTANCE,Central,123.0,Upton,39.3036,-76.6329,"(39.3036,-76.6329)",NaN,2010,2010

In [13]:
totals_by_year = df.year.value_counts().sort_index().reset_index()

In [14]:
df.year.value_counts()

year
2010    45224
2011    43364
2012    42333
2013    39542
2014    37078
2015    25732
2016    23089
2017    21989
2018    20543
2019    19407
2023    13566
2020    13162
2022    12360
2021    11130
Name: count, dtype: int64

In [15]:
totals_by_year = df.year.value_counts().sort_index().reset_index()

In [16]:
chart = dw.ColumnChart(title="Baltimore Arrests",data=totals_by_year)

In [17]:
chart.create()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='', source_url='', byline='', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [18]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='', source_url='', byline='', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [19]:
chart.display()

In [21]:
chart.source_name = "OpenBaltimore"
chart.source_url = "https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about"
chart.byline = "Caroline Jones"
chart.update()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Caroline Jones', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

chart.publish()

In [22]:
chart.display()

In [23]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Caroline Jones', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color=0, negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [24]:
chart.display()

In [25]:
chart.base_color = "#004FA2" #American University Blue

In [26]:
chart.update()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Caroline Jones', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#004FA2', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [27]:
chart.publish()

ColumnChart(chart_type='column-chart', data=    year  count
0   2010  45224
1   2011  43364
2   2012  42333
3   2013  39542
4   2014  37078
5   2015  25732
6   2016  23089
7   2017  21989
8   2018  20543
9   2019  19407
10  2020  13162
11  2021  11130
12  2022  12360
13  2023  13566, transformations=Transform(transpose=False, vertical_header=True, horizontal_header=True, column_order=[], column_format=ColumnFormatList(formats=[]), external_data='', use_datawrapper_cdn=True, upload_method='copy'), title='Baltimore Arrests', intro='', notes='', source_name='OpenBaltimore', source_url='https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about', byline='Caroline Jones', aria_description='', hide_title=False, language='en-US', theme='datawrapper', auto_dark_mode=False, dark_mode_invert=True, get_the_data=False, download_image=False, download_pdf=False, download_svg=False, embed=False, force_attribution=False, share_buttons=False, share_url='', logo=False, logo_id='', custom={}, forkable=True, chart_id='7EKqX', custom_ticks_x=None, custom_ticks_y=None, custom_range_x=None, custom_range_y=None, x_grid_format=None, y_grid_format=None, x_grid='off', y_grid='on', text_annotations=[], range_annotations=[], y_grid_labels='outside', y_grid_label_align='left', base_color='#004FA2', negative_color=None, color_category={}, category_labels={}, category_order=[], exclude_from_color_key=[], bar_padding=30, plot_height_mode='fixed', plot_height_fixed=300, plot_height_ratio=0.5, show_color_key=False, show_value_labels='hover', value_labels_format='', value_labels_placement='outside')

In [28]:
chart.display()

In [29]:
df.head()

,RowID,X,Y,IncidentNumber,ArrestNumber,Age,Gender,Race,ArrestDateTime,ArrestLocation,...,ChargeDescription,District,Post,Neighborhood,Latitude,Longitude,GeoLocation,Shape,Year,year
0,29,1.401347e+06,608148.870493,22L09338,23000037.0,39.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
1,30,1.401347e+06,608148.870493,22L09338,23000039.0,50.0,M,B,2022-12-31 23:50:00,4000 OAKFORD ST,...,HAND GUN VIOLATION,Northwest,621.0,West Arlington,39.3361,-76.6853,"(39.3361,-76.6853)",NaN,2022,2022
2,31,NaN,NaN,NaN,23000010.0,27.0,M,B,2022-12-31 23:40:00,NaN,...,FAILURE TO APPEAR,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022
3,32,1.417636e+06,595206.835862,22L09343,23000050.0,42.0,M,B,2022-12-31 23:15:00,500 DOLPHIN ST,...,HAND GUN VIOLATION,Central,123.0,Upton,39.3004,-76.6279,"(39.3004,-76.6279)",NaN,2022,2022
4,33,NaN,NaN,22L09312,22157183.0,43.0,F,W,2022-12-31 21:00:00,1500 BECKLOW AVE,...,STOLEN AUTO,NaN,NaN,NaN,NaN,NaN,"(,)",NaN,2022,2022

In [30]:
df.District.value_counts()

District
Western      29842
Central      28501
Eastern      28114
Southern     25780
Northeast    24180
Southeast    23710
Northwest    22044
Southwest    21822
Northern     13087
Name: count, dtype: int64

In [32]:
def create_chart(district: str) -> str:
    """Create a Datawrapper column chart of arrests by year in a Baltimore police district.
    
    Args:
        district: The name of the district to chart.

    Returns:
        The chart's embed code.
    """
    # Filter the dataframe to the provided district
    district_df = df[df.District == district]

    # Count the number of arrests in each year
    district_by_year = district_df.year.value_counts().sort_index().reset_index()

    # Create the chart with Datawrapper
    chart = dw.ColumnChart(
        # Use the district name in the title
        title=f"Arrests in Baltimore's {district} District",
        # Pass in the filtered data
        data=district_by_year,
        base_color="#004FA2",
        source_name="OpenBaltimore",
        source_url="https://data.baltimorecity.gov/datasets/baltimore::bpd-arrests/about",
        byline="First Automated Chart",
    )
    
    # Create the chart
    chart.create()

    # Publish the chart
    chart.publish()

    # Return the chart's embed code
    return chart.display()

In [33]:
create_chart("Western")

In [34]:
create_chart("Eastern")

In [35]:
# Create an empty list to hold the charts
chart_list = []

# Loop through the unique districts...
for district in df.District.dropna().unique():
    # Print a message to the console
    print(f"Creating chart for the {district} District")

    # Create a chart for the district and save it as a variable
    c = create_chart(district)

    # Add the chart to the list
    chart_list.append(c)

Creating chart for the Northwest District
Creating chart for the Central District
Creating chart for the Western District
Creating chart for the Eastern District
Creating chart for the Northeast District
Creating chart for the Southern District
Creating chart for the Southeast District
Creating chart for the Northern District
Creating chart for the Southwest District

In [36]:
from IPython.display import display

In [37]:
display (*chart_list)